### ISSUE TITLE
Pretrained CRIS model

### ISSUE THREAD

**Issue by OptimusLime** [DerrickWang005/CRIS.pytorch#3]
Are there any plans to host a pre-trained CRIS model on e.g. huggingface?

Looking forward to trying out the model!

**Comment by willyfh** [comment]
+1

**Comment by DerrickWang005** [comment]
Yes. We will release the pretrained models ASAP.

**Comment by OptimusLime** [comment]
@DerrickWang005 Any updates on this or timeline?

**Comment by Bo396543018** [comment]
+1

**Comment by saurabhya** [comment]
Hii @DerrickWang005, Can you upload the pre-trained model?

**Comment by sanchit88** [comment]
Hi @DerrickWang005 any update on releasing a pre-trained model? Thanks!

**Comment by qiruiw** [comment]
+1

**Comment by loris2222** [comment]
+1

**Comment by MaslikovEgor** [comment]
+1

**Comment by loris2222** [comment]
While we wait for the official pretrained model, I have trained CRIS on refcoco using the standard training procedure (default parameters, 50 epochs). The model is available [here](https://polimi365-my.sharepoint.com/:f:/g/personal/10524166_polimi_it/Ej-lkQiFHU1ArDG68PP-u3kBJL_UBvvn1scRU7Ps5fiIOw?e=KzFowg).
I should be able to keep it there for a couple of years, I think it will be enough for the authors to publish their model 😄

**Comment by MaslikovEgor** [comment]
@loris2222 do you have similar score on benchmark datasets?

**Comment by loris2222** [comment]
I am using the model for another purpose so I haven't saved the test performance, but you are welcome to try and report the results here. Anyways, qualitatively results are quite good.

**Comment by sanchit88** [comment]
Wow @loris2222 thank you so much. By the way, do you have any report or documentation regarding the results (qualitatively and quantitatively). It would be really nice and helpful to see the results and read more about it. Great work!

**Comment by MaslikovEgor** [comment]
@loris2222 @sanchit88 I have some bad news( 

test your model on evaluation RefCOCO data and I have this( 

IoU=8.03  Pr@50: 0.17  Pr@60: 0.17  Pr@70: 0.17  Pr@80: 0.09  Pr@90: 0.09

**Comment by MaslikovEgor** [comment]
@DerrickWang005 Should you please share pre-trained CRIS model with benchmark score(

**Comment by loris2222** [comment]
I have found the wandb final log:

`{
  "time/batch": 3.7636070251464844,
  "time/data": 0.017482995986938477,
  "training/lr": 0.00001,
  "training/loss": 0.014677105471491814,
  "training/iou": 89.92655944824219,
  "training/prec@50": 100,
  "_timestamp": 1665918932.9539435,
  "_runtime": 74153.98540353775,
  "_step": 33700,
  "_wandb": {
    "runtime": 74615
  }
}`

Maybe there is something wrong in your configuration?

**Comment by loris2222** [comment]
Yeah possibly, but results on training data were not published, so they still might be reasonable. By the way VOC is an entirely different dataset and it seems to be doing well as you see from the example (not cherry picked). As I said I'm using these models for something else so I don't think I will be able to run another 20h of training...

**Comment by BingliangLI** [comment]
> Yes. We will release the pretrained models ASAP.

Hi just want to ask if is there any update. I'm planning to do some further research with your model, could you please upload the checkpoints?

**Comment by BingliangLI** [comment]
@loris2222 @MaslikovEgor @OptimusLime @willyfh @qiruiw @saurabhya 

Just want to report my test result on @loris2222 's model(RefCOCO val):

```
2022-10-27 18:05:35 | INFO     | __main__:76 - => loading checkpoint 'exp/refcoco/CRIS_R50/best_model.pth'
2022-10-27 18:05:36 | INFO     | __main__:79 - => loaded checkpoint 'exp/refcoco/CRIS_R50/best_model.pth'
Inference:: 100%|###############################################| 3811/3811 [06:45<00:00,  9.39it/s]
2022-10-27 18:12:22 | INFO     | engine.engine:198 - => Metric Calculation <=
2022-10-27 18:12:22 | INFO     | engine.engine:211 - IoU=69.06
2022-10-27 18:12:22 | INFO     | engine.engine:213 - Pr@50: 80.93.
2022-10-27 18:12:22 | INFO     | engine.engine:213 - Pr@60: 76.44.
2022-10-27 18:12:22 | INFO     | engine.engine:213 - Pr@70: 69.83.
2022-10-27 18:12:22 | INFO     | engine.engine:213 - Pr@80: 53.51.
2022-10-27 18:12:22 | INFO     | engine.engine:213 - Pr@90: 17.09.
```


The result reported by the authors is 69.52, I think his mode is fine(69.06), thanks(a lot) for sharing!

**Comment by loris2222** [comment]
Glad to be of help :)

So @MaslikovEgor did you check again to see whether there were problems in your pipeline?

**Comment by RubenBMHMendes** [comment]
Thanks for the pre-trained model @loris2222. I am still trying to better understand the functionalities and I was wondering if you could detail on how to load the weights and use the model?

**Comment by loris2222** [comment]
Just put the linked `.pth` in `<CRIS_root_folder>/exp/refcoco/CRIS_50` and follow the instructions from this repo's readme.

**Comment by RubenBMHMendes** [comment]
I did the following:
- Clone the repo to colab;
- Update `<CRIS_root_folder>/config/refcoco/cris_r50.yaml` to consider the `.pth` as `clip_pretrain: /content/best_model.pth`;
- Run evaluation code in readme;
```
# e.g., Evaluation on the val-set of the RefCOCO dataset
CUDA_VISIBLE_DEVICES=0 python -u test.py \
      --config config/refcoco/cris_r50.yaml \
      --opts TEST.test_split val-test \
             TEST.test_lmdb datasets/lmdb/refcocog_g/val.lmdb
```
Got the error below. I do not understand the root cause..

2022-10-27 16:34:07.855 | ERROR    | __main__:<module>:90 - An error has been caught in function '<module>', process 'MainProcess' (222), thread 'MainThread' (139848918288256):
Traceback (most recent call last):

> File "/content/CRIS.pytorch/test.py", line 90, in <module>
    main()
    └ <function main at 0x7f308a052b00>

  File "/content/CRIS.pytorch/test.py", line 70, in main
    model, _ = build_segmenter(args)
               │               └ CfgNode({'dataset': 'refcoco', 'train_lmdb': 'datasets/lmdb/refcoco/train.lmdb', 'train_split': 'train', 'val_lmdb': 'dataset...
               └ <function build_segmenter at 0x7f309690e290>

  File "/content/CRIS.pytorch/model/__init__.py", line 33, in build_segmenter
    model = CRIS(args)
            │    └ CfgNode({'dataset': 'refcoco', 'train_lmdb': 'datasets/lmdb/refcoco/train.lmdb', 'train_split': 'train', 'val_lmdb': 'dataset...
            └ <class 'model.segmenter.CRIS'>

  File "/content/CRIS.pytorch/model/segmenter.py", line 15, in __init__
    map_location="cpu").eval()

  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
                 │     │  │                │       │   │             └ {}
                 │     │  │                │       │   └ device(type='cpu')
                 │     │  │                │       └ '/content/best_model.pth'
                 │     │  │                └ <torch.jit.CompilationUnit object at 0x7f308a068b30>
                 │     │  └ <built-in method import_ir_module of PyCapsule object at 0x7f3098a21a80>
                 │     └ <module 'torch._C' from '/usr/local/lib/python3.7/dist-packages/torch/_C.cpython-37m-x86_64-linux-gnu.so'>
                 └ <module 'torch' from '/usr/local/lib/python3.7/dist-packages/torch/__init__.py'>

RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by BingliangLI** [comment]
@RubenBMHMendes You have to download pre-trained CLIP first(it's not `best_model.pth`) from [here](https://openaipublic.azureedge.net/clip/models/afeb0e10f9e5a86da6080e35cf09123aca3b358a0c3e3b6c78a7b63bc04b6762/RN50.pt) , it's from the [official CLIP repo](https://github.com/openai/CLIP/blob/main/clip/clip.py).

Then put `best_model.pth` at `<CRIS_root_folder>/exp/refcoco/CRIS_50` and you are all set.

**Comment by RubenBMHMendes** [comment]
@BingliangLI thanks for your answer! I downloaded the RN50 model and created a pretrained folder in <CRIS_root_folder> and added best_model.pth in the correct directory but I got the same error as before.

Does anyone have a minimum working example on this? I can also share the colab notebook.

**Comment by RubenBMHMendes** [comment]
> I have found the wandb final log for my training process:
> 
> `{ "time/batch": 3.7636070251464844, "time/data": 0.017482995986938477, "training/lr": 0.00001, "training/loss": 0.014677105471491814, "training/iou": 89.92655944824219, "training/prec@50": 100, "_timestamp": 1665918932.9539435, "_runtime": 74153.98540353775, "_step": 33700, "_wandb": { "runtime": 74615 } }`
> 
> Qualitative results on VOC ![image](https://user-images.githubusercontent.com/1367018/197825523-3a9f11a0-4366-478a-993f-40eb5fca6166.png)
> 
> Maybe there is something wrong in your configuration?

Hi @loris2222, how did you extract the segmentation mask with a custom image using your best_model?

**Comment by rabinadk1** [comment]
> Yes. We will release the pretrained models ASAP.

@DerrickWang005, Any update on this?

**Comment by Zhenchong-Hu** [comment]
I fine-turned this model and opensourced it,  see [PEFT_CRIS](https://github.com/Huzhenchong/PEFT_CRIS) for anyone who may need

**Comment by Jeffry1997** [comment]
> I fine-turned this model and opensourced it, see [PEFT_CRIS](https://github.com/Huzhenchong/PEFT_CRIS) for anyone who may need

Hi, thanks a lot for sharing PEFT_CRIS!

It seems that the link / repo for PEFT_CRIS is currently not accessible (the site appears to be down / I’m getting an error when trying to open it).
Could you please check if the link is still valid or share an updated URL?

Also, I am training the original CRIS model with the default hyperparameters. During training I observe clear signs of overfitting: the training IoU is about 15 points higher than the validation IoU.
Is this gap expected in your experiments, or did you use any additional tricks (e.g., stronger data augmentation, regularization, early stopping, etc.) to reduce overfitting?

Thanks again for your work and for open-sourcing the code!

<img width="472" height="306" alt="Image" src="https://github.com/user-attachments/assets/e733b575-5d69-4a0a-82f5-215c06435895" />

<img width="519" height="356" alt="Image" src="https://github.com/user-attachments/assets/ed37725a-1f53-4d6f-b947-c34997a70383" />
